<a href="https://colab.research.google.com/github/Hannah1123/Learning_Attention_is_all_you_need/blob/master/Attention_aftermeeting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class clones(N):
  return 


In [ ]:
class Encoder(torch.nn.module):
  def __init__(self, layer, N):
    super(Encoder, self).__init__()
    self.layers = [layer]*N


  def forword(self, ):


In [ ]:
import torch
help(torch.nn.Conv2d)

nn.Conv2d的功能是：对由多个输入平面组成的输入信号进行二维卷积，以最简单的例子进行说明：

输入信号的形式为(N,Cin,H,W)(N,C_{in},H,W)   
N表示batch size，  
Cin表示channel个数，即每个卷积层中卷积核的数量，RGB图片channel个数为3  
H，W分别表示特征图的高和宽。


In [ ]:
import torch
import torch.nn as nn

class PNet(nn.Module):
  def __init__(self):
    super(PNet, self).__init__()
    self.conv1 = torch.nn.Conv2d(3, 32, 3, 1, 1)
    self.relu1 = torch.nn.ReLU()
    self.conv2 = torch.nn.Conv2d(3, 32, 3, 1, 1)
    self.rulu2 = torch.nn.ReLU()
    self.maxpool1 = torch.nn.MaxPool2d(2, 1)
    self.maxpool2 = torch.nn.MaxPool2d(2, 1)

  def forword(x):
    x = self.conv1(x)
    x = self.relu1(x)
    x = self.maxpool1(x)
    x = self.conv2(x)
    x = self.relu2(x)
    x = self.maxpool2(x)
    return x

model = PNet()
print(model)






PNet(
  (conv1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (relu1): ReLU()
  (conv2): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (rulu2): ReLU()
  (maxpool1): MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)
  (maxpool2): MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)
)


In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import math, copy, time
from torch.autograd import Variable
import matplotlib.pyplot as plt
import seaborn
seaborn.set_context(context="talk")
%matplotlib inline

In [ ]:
class clones(module, N):
  return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])

SyntaxError: ignored

In [ ]:
def clones(module, N):
  return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])

In [ ]:
class Encoder(nn.Module):
  def __init__(self, layer, N):
    super(Encoder,self).__init__()
    self.layers = clones(layer, N)
    self.norm = LayerNorm()

  def forword(self, x):
    for layer in self.layers:
      x = layer(x)
      x = self.norm(x)
    return x
    

In [ ]:
class LayerNorm(nn.Module):
  def __init__(self, layer):
    super(Layer, self).__init__()
    self.LayerNorm = nn.LayerNorm()


  def forword(self, x):
    x = self.LayerNorm

    return x

In [ ]:
class SublayerConnection(nn.Module):
  def __init__(self, size):
    super(SublayerConnection, self).__init__()
    self.sublayer = LayerNorm(size)

  def forword(self, x):
    return x + self.sublayer(x)

In [ ]:
class EncoderLayer(nn.Module):
  def __init__(self, ):
    super(EncoderLayer, self).__init__()
    self.atten = Attention(sublayer)
    self.norm = LayerNorm(size)
    self.sublayerconnection = SublayerConnection()

  def forword(self, ):
    x = self.atten(x)
    x = slef.sublayerconnection(x)

decoder


In [ ]:
class DEcoder(nn.Module):
  def __init__(self, layer, N):
    super(Decoder,self).__init__()
    self.layers = clones(layer, N)
    self.norm = LayerNorm()

  def forword(self, x):
    for layer in self.layers:
      x = layer(x)
      x = self.norm(x)
    return x

##attention

In [ ]:
def attention(quary, key, value, mask=None, dropout=None):

  d_k = query.size(-1)
  scores = torch.matmul(query, key.transpose(-2, -1)) / math.sqrt(d_k)
  #matmul：高维向量乘法  transpose：转置最后一维和倒数第二维换位置 
  if mask is not None:
    scores = scores.masked_fill(mask == 0, -1e9)
  p_attn = F.softmax(scores, dim = -1) 
  # dim=0表示按列计算；dim=1表示按行计算，dim=-1,即,以最后一个维度作为一维向量计算softmax
  if dropout is not None:
    p_attn = dropout(p_attn)
  return torch.matmul(p_atten, value), p_attn



In [ ]:
scores = torch.matmul(query, key.transpose(-2, -1)) / math.sqrt(d_k)

In [ ]:
import torch
a = torch.ones(3, 4)
b = torch.ones(5, 4, 2)
c = torch.ones(2, 3)
print('a', a)
print('b', b)
print('c', c)

y = torch.matmul(c, a)
print('y', y)
x = torch.matmul(a, b)
print('x', x)

In [ ]:
EMBEDDING_DIM = 512 
DIM_FF = 2048
DIM_Q = DIM_K = DIM_V= 64
NUM_OF_HEAD = 8
EXPECTED_MAX_NUM_WORD = 100 #??
BATCH_SIZE = 32 #RANDOM

In [ ]:
torch.manual_seed(1)
input = torch.randn(BATCH_SIZE, EXPECTED_MAX_NUM_WORD, EMBEDDING_DIM)
w_q = torch.randn(EMBEDDING_DIM, DIM_Q)
w_k = torch.randn(EMBEDDING_DIM, DIM_K)
w_v = torch.randn(EMBEDDING_DIM, DIM_V)
# .view()即reshape
query = torch.matmul(input.view(BATCH_SIZE*EXPECTED_MAX_NUM_WORD, EMBEDDING_DIM), w_q)
query = query.view(BATCH_SIZE, EXPECTED_MAX_NUM_WORD, DIM_Q)
query_1 = torch.matmul(input, w_q)
print(torch.all(query==query_1))

key = torch.matmul(input, w_k)
value = torch.matmul(input, w_v)


tensor(True)


In [ ]:
import math
import numpy as np
d_k = query.size(-1)
scores = torch.matmul(query, key.transpose(-2, -1)) / math.sqrt(d_k)

print(query.shape)
print(key.shape)
print(key.transpose(-1, -2).shape)
print(scores.shape)
print(torch.all(scores[0]==torch.matmul(query[0], key.transpose(-1,-2)[0]/np.sqrt(DIM_Q))))

torch.Size([32, 100, 64])
torch.Size([32, 100, 64])
torch.Size([32, 64, 100])
torch.Size([32, 100, 100])
tensor(True)


##multihead attention

In [ ]:
class MultiHeadedAttention(nn.Module):
  def __init__(self, h, d_model, dropout=0.1):
    super(MultiHeadedAttention, self).__init__()
    assert d_model % h == 0 
    #假设 d_v 永远等于 d_k 
    self.d_k = d_model // h  #减少维度使总计算量相当于single-head用全维度计算 512/8=64维
    self.h = h   #取h=8
    self.attn = None
    self.linears = clones(nn.Linear(d_model, d_model), 4)
    self.dropout = nn.Dropout(p=dropout)

  def forward(self, query, key, value, mask=None):
    if mask is not None:
      #同一个mask 用于所有h head
      mask = mask.unsqueeze(1) #在1的位置加入维度为1的维度，如原来为（4，3），就变为（4，1，3） 
    nbatches = query.size(0)  #0维上的元素个数
  
    "1）线性投影 从d_model到 h*d_k"
    query, key, value = [l(x).view(nbatches, -1, self.h, self.d_k).transpose(1, 2) for l, x in zip(self.linears, (query, key, value))]
                 # view（）函数：重塑张量维形状(nbatches, -1, self.h, self.d_k)，（-1表示未知，由计算机自己算），之后 转置（1，2）

    "2）应用attention到投影向量上"
    x, self.attn = attention(query, key, value, mask=mask, dropout = self.dropout)

    "3）Concat using a view and apply a final linear. "
    x = x.transpose(1, 2).contiguous().view(nbatches, -1, self.h*self.d_k)
    return self.linears[-1](x)

In [ ]:
x = torch.randn(128, 20)  # 输入的维度是（128，20）
m = torch.nn.Linear(20, 30)  # 20,30是指维度
output0 = m(x)
output0.shape


torch.Size([128, 30])

In [ ]:
#linear function: 把query变成可学习的参数
#linears = clones(nn.Linear(d_model, d_model), 4)
l = nn.Linear(64, 64)
x = query
output = l(x)
print('query.shape:', query.shape)
print('output.shape:', output.shape)
#query, key, value = [l(x).view(nbatches, -1, self.h, self.d_k).transpose(1, 2) for l, x in zip(self.linears, (query, key, value))]

query.shape: torch.Size([32, 100, 64])
output.shape: torch.Size([32, 100, 64])


In [ ]:
query.size(0)

32

In [ ]:
nbatches = query.size(0)
d_k = 64
h = 4
query = l(x).view(nbatches, -1, h, d_k).transpose(1, 2)
query.shape

torch.Size([32, 4, 25, 64])

In [ ]:
linears = clones(nn.Linear(64, 64), 4)
query, key, value = [l(x).view(nbatches, -1, h, d_k).transpose(1, 2) for l, x in zip(linears, (query, key, value))]

In [ ]:
x, attn = attention(query, key, value)

NameError: ignored

In [ ]:
t = torch.arange(320).reshape(10, 32)
print('t:', t)

t: tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
          46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
          60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
          92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
         142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
         156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [ ]:
t0 = t.view(10, 4, 8)
print('t0:', t0)

t0: tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [  8,   9,  10,  11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29,  30,  31]],

        [[ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62,  63]],

        [[ 64,  65,  66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87],
         [ 88,  89,  90,  91,  92,  93,  94,  95]],

        [[ 96,  97,  98,  99, 100, 101, 102, 103],
         [104, 105, 106, 107, 108, 109, 110, 111],
         [112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127]],

        [[128, 129, 130, 131, 132, 133, 134, 135],
         [136, 137, 138, 139, 140, 141, 142, 143],
         [144, 145, 146, 147, 148, 149, 150, 151],
         [152, 153,

In [ ]:
t1 = t0.transpose(0, 1)
print('t1:', t1)

t1: tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 64,  65,  66,  67,  68,  69,  70,  71],
         [ 96,  97,  98,  99, 100, 101, 102, 103],
         [128, 129, 130, 131, 132, 133, 134, 135],
         [160, 161, 162, 163, 164, 165, 166, 167],
         [192, 193, 194, 195, 196, 197, 198, 199],
         [224, 225, 226, 227, 228, 229, 230, 231],
         [256, 257, 258, 259, 260, 261, 262, 263],
         [288, 289, 290, 291, 292, 293, 294, 295]],

        [[  8,   9,  10,  11,  12,  13,  14,  15],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 72,  73,  74,  75,  76,  77,  78,  79],
         [104, 105, 106, 107, 108, 109, 110, 111],
         [136, 137, 138, 139, 140, 141, 142, 143],
         [168, 169, 170, 171, 172, 173, 174, 175],
         [200, 201, 202, 203, 204, 205, 206, 207],
         [232, 233, 234, 235, 236, 237, 238, 239],
         [264, 265, 266, 267, 268, 269, 270, 271],
         [296, 297, 298, 

In [ ]:
t2 = t.view(4, 10, 8)
print('t2:', t2)

t2: tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [  8,   9,  10,  11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29,  30,  31],
         [ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62,  63],
         [ 64,  65,  66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84,  85,  86,  87],
         [ 88,  89,  90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101, 102, 103],
         [104, 105, 106, 107, 108, 109, 110, 111],
         [112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127],
         [128, 129, 130, 131, 132, 133, 134, 135],
         [136, 137, 138, 139, 140, 141, 142, 143],
         [144, 145, 146, 147, 148, 149, 150, 151],
         [152, 153, 154, 

##Embedding

我们需要建立神经网络通过learning的办法修改word embedding里面的参数使得word embedding每一个词向量能够表示每一个不同的词

In [ ]:
class Embedding(nn.Module):
  def __init__(self, vocab, d_model):
    super(Embedding, self).__init__()
    self.vocab = vocab
    self.d_model = d_model
    self.embed = nn.Embedding(vocab, d_model) #每句话里有几个单词， 每个单词的维度

  def forward(self. x):
    x = self.embed(x)
  return x * math.sqrt(self.d_model) # ??



##Positional Encoding

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p = torch.arange(0, 10).unsqueeze(1)
p.shape

torch.Size([10, 1])

In [ ]:
torch.arange(0, 64, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])

In [ ]:
torch.arange(0, 64, 2) * -(math.log(10000.0) / 64)

In [ ]:
torch.exp(torch.arange(0, 64, 2) * -(math.log(10000.0) / 64))

tensor([1.0000e+00, 7.4989e-01, 5.6234e-01, 4.2170e-01, 3.1623e-01, 2.3714e-01,
        1.7783e-01, 1.3335e-01, 1.0000e-01, 7.4989e-02, 5.6234e-02, 4.2170e-02,
        3.1623e-02, 2.3714e-02, 1.7783e-02, 1.3335e-02, 1.0000e-02, 7.4989e-03,
        5.6234e-03, 4.2170e-03, 3.1623e-03, 2.3714e-03, 1.7783e-03, 1.3335e-03,
        1.0000e-03, 7.4989e-04, 5.6234e-04, 4.2170e-04, 3.1623e-04, 2.3714e-04,
        1.7783e-04, 1.3335e-04])

In [ ]:
div = torch.exp(torch.exp(torch.arange(0, 64, 2) * -(math.log(10000.0) / 64)))
div.shape

torch.Size([32])

In [ ]:
pe = torch.zeros(5000, 64)
position = torch.arange(0, 5000).unsqueeze(1)

In [ ]:
pe[:, 0::2] = torch.sin(position * div) #偶数位
pe[:, 1::2] = torch.cos(position * div)
pe.shape

torch.Size([5000, 64])

In [ ]:
pe = pe.unsqueeze(0)
pe.shape

torch.Size([1, 5000, 64])

In [ ]:
print(pe[0][100])

tensor([ 0.9968, -0.0803, -0.9287, -0.3708, -0.4364,  0.8998,  0.9962, -0.0872,
        -0.8603,  0.5098,  0.8902,  0.4555,  0.0814,  0.9967,  0.9199,  0.3921,
        -0.5323, -0.8465,  0.8266,  0.5627, -0.8571,  0.5152, -0.5928, -0.8053,
         0.4437, -0.8962,  0.9559, -0.2936,  0.9531,  0.3028,  0.7253,  0.6884,
         0.4565,  0.8897,  0.2199,  0.9755,  0.0329,  0.9995, -0.1082,  0.9941,
        -0.2126,  0.9771, -0.2893,  0.9572, -0.3457,  0.9383, -0.3871,  0.9220,
        -0.4177,  0.9086, -0.4403,  0.8978, -0.4571,  0.8894, -0.4696,  0.8829,
        -0.4788,  0.8779, -0.4858,  0.8741, -0.4910,  0.8712, -0.4948,  0.8690])


In [ ]:
class PositionEncoding(nn.Module):
  def __init__(self, d_model, max_len=5000, droput):
    super(PositionEncoding, self).__init__()
    self.dropout = nn.Dropout()

    position = torch.arange(0, max_len).unsqueeze(1)
    div = torch.exp(torch.arange(0, d_model, 2) * -(math.log(10000) / d_model))
    pe = torch.zeros(max_len, d_model)
    pe[:, 0::2] = sin(position * div)
    pe[:, 1::2] = cos(position * div)
    pe = pe.unsqueeze(0)
    self.register_buffer('pe', pe)

  def forward(self, x):
    x = 


疑问1：为什么不把参数都设置为nn.Parameter类型，只是把不需要更新参数的设置 requires_grad=False?

疑问2：为什么不直接将不需要进行参数修改的变量作为模型类的成员变量就好了，还要进行注册?

对于疑问1我没找到答案，疑问2有两个原因:

不进行注册，参数不能保存到 OrderDict，也就无法进行保存
模型进行参数在CPU和GPU移动时, 执行 model.to(device) ，注册后的参数也会自动进行设备移动